services:
  - type: web
    name: amirballbot
    runtime: docker
    plan: starter
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
